package com.bc.application.service.impl;

import com.bc.application.domain.CryptogramRequest;
import com.bc.application.domain.CryptogramResponse;
import com.bc.application.enumeration.CryptogramVersionNumber;
import com.bc.application.enumeration.EMVUDKDerivationMethod;
import com.bc.application.enumeration.PaymentScheme;
import com.bc.application.port.in.rest.cryptogramfunctions.command.GenerateApplicationCryptogramCommand;
import com.bc.application.port.in.rest.cryptogramfunctions.mapper.GenerateACCommandToDomainMapper;
import com.bc.application.service.CryptogramFunctionsService;
import com.bc.utilities.*;
import jakarta.enterprise.context.ApplicationScoped;
import lombok.extern.slf4j.Slf4j;

import java.util.LinkedHashMap;
import java.util.Map;
/**
 * Core domain service hosting the methods for performing Visa Payment scheme specific cryptogram related functions.
 */
@Slf4j
@ApplicationScoped
public class VisaCryptogramServiceImpl
        extends CryptogramFunctionsService<GenerateApplicationCryptogramCommand,
        GenerateACCommandToDomainMapper>
        implements LoggerUtility {
    private Map<String, String> mappedIad = new LinkedHashMap<>();
    private String uniqueDerivationKey;
    private String applicationCryptogramKey;
    private CryptogramVersionNumber cryptogramVersionNumber;
    private String cardVerificationResults;
    private PaymentScheme paymentScheme;
    /**
     * Driver method for generating an Application Cryptogram.
     * @param command Command object with the Application Cryptogram generation request.
     * @return CryptogramResponse domain object with the generated cryptogram value.
     */
    @Override
    public CryptogramResponse getApplicationCryptogram(GenerateApplicationCryptogramCommand command) {
        logDebug(log, "Command object received: {}.", command);
        CryptogramRequest cryptogramRequest = buildDomainObjectFromCommand(command);
        logDebug(log, "Domain objectCommand mapped from command: {}.", cryptogramRequest);
        setPaymentScheme(cryptogramRequest.getPan());
        parsedIadAndSetCvnCvr(cryptogramRequest.getIssuerApplicationData());
        setApplicationCryptogramKey(cryptogramRequest);
        // Generate Visa cryptogram, and build and return REST API response object
        return buildResponseObjectFromDomain(generateCryptogram(cryptogramRequest,
                applicationCryptogramKey,
                cryptogramVersionNumber,
                cardVerificationResults)
        );
    }
    /**
     * Method to build and map the command object to Cryptogram Request domain object.
     * @param command Application Cryptogram Request command object.
     * @return CryptogramRequest domain object generated by mapping command object.
     */
    @Override
    protected CryptogramRequest buildDomainObjectFromCommand(GenerateApplicationCryptogramCommand command) {
        return commandToDomainMapper.mapGenerateACCommandToDomain(command);
    }
    /**
     * Set Payment Scheme based on the first digit of PAN.
     */
    @Override
    protected void setPaymentScheme(String pan){
        paymentScheme = DeterminePaymentScheme.fromPan(pan);
        logDebug(log, "Payment Scheme set based on PAN: {}.", paymentScheme);
    }
    /**
     * Call Payment Scheme specific IAD parser with IAD from request as input and get a parsed IAD map, and setup CVN and CVR
     * from the parsed IAD.
     * @param issuerApplicationData IAD from request.
     */
    @Override
    protected void parsedIadAndSetCvnCvr(String issuerApplicationData){
        mappedIad = new VisaIADParser(issuerApplicationData).parseIad();
        logDebug(log, "Mapped IAD: {}.", mappedIad);
        setCvnFromMappedIad();
        setCvrFromMappedIad();
    }
    /**
     * Search mapped IAD data using key "CVN" and set the Cryptogram Version Number based on the value.
     */
    @Override
    protected void setCvnFromMappedIad(){
        final String CVN_NAME = "CVN";
        cryptogramVersionNumber = CryptogramVersionNumber.valueOf(
                mappedIad.get(CVN_NAME)
        );
        logDebug(log, "CVN set based on mapped IAD: {}.", cryptogramVersionNumber);
    }
    /**
     * Search mapped IAD data using key "CVR" and set the Card Verification Results based on the value.
     */
    @Override
    protected void setCvrFromMappedIad(){
        final String CVR_NAME = "CVR";
        cardVerificationResults = mappedIad.get(
                CVR_NAME
        );
        logDebug(log, "CVR set based on mapped IAD: {}.", cardVerificationResults);
    }
    /**
     * Driver method which derives Unique Derivation Key from Issuer Master Key, and subsequently derives a Session Key
     * from the derives Unique Derivation Key.
     * @param cryptogramRequest CryptogramRequest domain object mapped from command.
     */
    @Override
    protected void setApplicationCryptogramKey(CryptogramRequest cryptogramRequest){
        buildUniqueDerivationKeyFromIssuerMasterKey(cryptogramRequest);
        buildSessionKeyFromUniqueDerivationKey(cryptogramRequest.getApplicationTransactionCounter(),
                cryptogramRequest.getUnpredictableNumber()
        );
    }
    /**
     * Build Unique Derivation Key from the Issuer Master Key received from input.
     * @param cryptogramRequest CryptogramRequest domain object mapped from command.
     */
    @Override
    protected void buildUniqueDerivationKeyFromIssuerMasterKey(CryptogramRequest cryptogramRequest){
        uniqueDerivationKey = getUniqueDerivationKey(cryptogramRequest.getIssuerMasterKey(),
                cryptogramRequest.getPan(),
                cryptogramRequest.getPanSequenceNumber(),
                cryptogramVersionNumber
        );
        logDebug(log, "UDK generated: {}.", uniqueDerivationKey);
    }
    /**
     * Build Session Key from the derived Unique Derivation Key.
     * @param applicationTransactionCounter ApplicationTransactionCounter from input.
     */
    @Override
    protected void buildSessionKeyFromUniqueDerivationKey(String applicationTransactionCounter, String unpredictableNumber){
        applicationCryptogramKey = getSessionKey(uniqueDerivationKey,
                applicationTransactionCounter,
                unpredictableNumber,
                cryptogramVersionNumber
        );
        logDebug(log, "Session Key generated: {}.", applicationCryptogramKey);
    }
    /**
     * Method to derive Unique Derivation Key (UDK) from Issuer Master Key (IMK) for cryptogram generation.
     * @param issuerMasterKey Issuer Master Key from request.
     * @param pan Primary Account Number from request.
     * @param panSequenceNumber PAN sequence number from request.
     * @param cryptogramVersionNumber Cryptogram version number determined from Issuer Application Data.
     * @return UDK generated from IMK.
     */
    @Override
    protected String getUniqueDerivationKey(String issuerMasterKey,
                                            String pan,
                                            String panSequenceNumber,
                                            CryptogramVersionNumber cryptogramVersionNumber) {
        EMVUniqueDerivationKeyDerivator emvUdkDerivator = new EMVUniqueDerivationKeyDerivator(issuerMasterKey,
                pan,
                panSequenceNumber,
                paymentScheme,
                cryptogramVersionNumber,
                EMVUDKDerivationMethod.METHOD_A
        );
        // The UDK derivation must be enhanced for CVN 22, as CVN 22 uses METHOD_B.
        return emvUdkDerivator.generateUniqueDerivationKey();
    }
    /**
     * Method to derive Unique Derivation Key (UDK) from Issuer Master Key (IMK) for cryptogram generation.
     * @param uniqueDerivationKey UDK derived from IMK.
     * @param applicationTransactionCounter Application Transaction Counter from request.
     * @param unpredictableNumber Unpredictable Number from input.
     * @param cryptogramVersionNumber Cryptogram version number determined from Issuer Application Data.
     * @return Session Key generated from UDK.
     */
    @Override
    protected String getSessionKey(String uniqueDerivationKey,
                                   String applicationTransactionCounter,
                                   String unpredictableNumber,
                                   CryptogramVersionNumber cryptogramVersionNumber) {
        EMVSessionKeyDerivator emvSessionKeyDerivator = new EMVSessionKeyDerivator(uniqueDerivationKey,
                applicationTransactionCounter,
                unpredictableNumber,
                cryptogramVersionNumber,
                paymentScheme
        );
        return emvSessionKeyDerivator.generateSessionKey();
    }
    /**
     * Method to build and map the Cryptogram Response domain object to Response DTO class.
     * @param arqc Application Cryptogram generated.
     * @return CryptogramResponse object containing generated Application Cryptogram.
     */
    @Override
    protected CryptogramResponse buildResponseObjectFromDomain(String arqc) {
        CryptogramResponse cryptogramResponse = new CryptogramResponse();
        cryptogramResponse.setRequestCryptogram(arqc);
        logDebug(log, "Response object generated: {}.", cryptogramResponse);
        return cryptogramResponse;
    }
    /**
     * Method to call the Payment Scheme specific cryptogram generation request.
     * @param cryptogramRequest Cryptogram Request domain object.
     * @return Application Cryptogram generated by Payment Scheme specific service.
     */
    @Override
    protected String generateCryptogram(CryptogramRequest cryptogramRequest,
                                        String sessionKey,
                                        CryptogramVersionNumber cryptogramVersionNumber,
                                        String cardVerificationResults) {
        VisaApplicationCryptogramGenerator visaApplicationCryptogramGenerator = new VisaApplicationCryptogramGenerator();
        return visaApplicationCryptogramGenerator
                .generateVisaApplicationCryptogram(cryptogramRequest,
                        sessionKey,
                        cryptogramVersionNumber,
                        cardVerificationResults
                );
    }
}